/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author jamdr
 */
public class PrincipalJFrame extends javax.swing.JFrame {

    /**
     * Creates new form PrincipalJFrame
     */
    RegPacienteInternalFrame regPacienteInternalFrame;
    ConsPacienteInternalFrame consPacienteInternalFrame;
    CitasInternalFrame citasInternalFrame;
    TratamientosInternalFrame tratamientosInternalFrame;
    MedicosInternalFrame medicosInternalFrame;
    ConsultorioInternalFrame consultorioInternalFrame;
 
    public PrincipalJFrame() throws SQLException {

        regPacienteInternalFrame = new RegPacienteInternalFrame();
        consPacienteInternalFrame = new ConsPacienteInternalFrame();
        citasInternalFrame= new CitasInternalFrame();
        tratamientosInternalFrame= new TratamientosInternalFrame();
        medicosInternalFrame= new MedicosInternalFrame();
        consultorioInternalFrame= new ConsultorioInternalFrame();
        add(regPacienteInternalFrame);
        add(consPacienteInternalFrame);
        add(citasInternalFrame);
        add(tratamientosInternalFrame);
        add(medicosInternalFrame);
        add(consultorioInternalFrame);
        setExtendedState(MAXIMIZED_HORIZ);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nombre = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        txtArchivo = new javax.swing.JMenu();
        txtSalir = new javax.swing.JMenuItem();
        txtCitas = new javax.swing.JMenuItem();
        txtTratamientos = new javax.swing.JMenuItem();
        txtMedicos = new javax.swing.JMenuItem();
        txtConsultorio = new javax.swing.JMenuItem();
        txtPaciente = new javax.swing.JMenu();
        txtRegistrar = new javax.swing.JMenuItem();
        txtConsultar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GESTION DE CITAS");
        setName("PrincipalJFrame"); // NOI18N

        nombre.setText("nombre");

        txtArchivo.setText("Archivo");
        txtArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtArchivoActionPerformed(evt);
            }
        });

        txtSalir.setText("Salir");
        txtSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSalirActionPerformed(evt);
            }
        });
        txtArchivo.add(txtSalir);

        txtCitas.setText("Citas");
        txtCitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCitasActionPerformed(evt);
            }
        });
        txtArchivo.add(txtCitas);

        txtTratamientos.setText("Tratamientos");
        txtTratamientos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTratamientosActionPerformed(evt);
            }
        });
        txtArchivo.add(txtTratamientos);

        txtMedicos.setText("Medicos");
        txtMedicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMedicosActionPerformed(evt);
            }
        });
        txtArchivo.add(txtMedicos);

        txtConsultorio.setText("Consultorio");
        txtConsultorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtConsultorioActionPerformed(evt);
            }
        });
        txtArchivo.add(txtConsultorio);

        jMenuBar1.add(txtArchivo);

        txtPaciente.setText("Paciente");

        txtRegistrar.setText("Registrar");
        txtRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRegistrarActionPerformed(evt);
            }
        });
        txtPaciente.add(txtRegistrar);

        txtConsultar.setText("Consultar");
        txtConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtConsultarActionPerformed(evt);
            }
        });
        txtPaciente.add(txtConsultar);

        jMenuBar1.add(txtPaciente);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(341, Short.MAX_VALUE)
                .addComponent(nombre)
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(419, Short.MAX_VALUE)
                .addComponent(nombre)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSalirActionPerformed
       System.exit(0);   // TODO add your handling code here:
    }//GEN-LAST:event_txtSalirActionPerformed

    private void txtRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRegistrarActionPerformed
     regPacienteInternalFrame.setVisible(true);   // TODO add your handling code here:
    }//GEN-LAST:event_txtRegistrarActionPerformed

    private void txtConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtConsultarActionPerformed
     consPacienteInternalFrame.setVisible(true);   // TODO add your handling code here:
    }//GEN-LAST:event_txtConsultarActionPerformed

    private void txtCitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCitasActionPerformed
     citasInternalFrame.setVisible(true);  // TODO add your handling code here:
    }//GEN-LAST:event_txtCitasActionPerformed

    private void txtTratamientosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTratamientosActionPerformed
      tratamientosInternalFrame.setVisible(true);    // TODO add your handling code here:
    }//GEN-LAST:event_txtTratamientosActionPerformed

    private void txtArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtArchivoActionPerformed
      // TODO add your handling code here:
    }//GEN-LAST:event_txtArchivoActionPerformed

    private void txtMedicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMedicosActionPerformed
       medicosInternalFrame.setVisible(true); // TODO add your handling code here:
    }//GEN-LAST:event_txtMedicosActionPerformed

    private void txtConsultorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtConsultorioActionPerformed
     consultorioInternalFrame.setVisible(true);   // TODO add your handling code here:
    }//GEN-LAST:event_txtConsultorioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new PrincipalJFrame().setVisible(true);
                } catch (SQLException e) {
                    Logger.getLogger(PrincipalJFrame.class.getName()).log(Level.SEVERE,null,e);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JMenuBar jMenuBar1;
    public javax.swing.JLabel nombre;
    public javax.swing.JMenu txtArchivo;
    public javax.swing.JMenuItem txtCitas;
    public javax.swing.JMenuItem txtConsultar;
    public javax.swing.JMenuItem txtConsultorio;
    public javax.swing.JMenuItem txtMedicos;
    public javax.swing.JMenu txtPaciente;
    public javax.swing.JMenuItem txtRegistrar;
    public javax.swing.JMenuItem txtSalir;
    public javax.swing.JMenuItem txtTratamientos;
    // End of variables declaration//GEN-END:variables
}
